# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
    working-directory: cmd

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.x'

    - name: Build
      run: go build -o ./bin/main ./...
      
    - name: See results
      run: ./bin/main
      
#    - name: Run & output
#      run: ./bin/main > results.txt
      
#    - name: Upload Go results
#      uses: actions/upload-artifact@v3
#      with:
#        name: Go-results
#        path: results.txt
        
